[project]
name = "2025"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "black==25.1.0",
    "graphviz==0.21",
    "pydantic>=2.11.7",
    "requests==2.32.5",
    "requests-toolbelt==1.0.0",
    "rich>=14.1.0",
    "typer>=0.17.4",
]
